name: Deploy Content to offboardingtestamirs [58d51aca-8596-4d2c-bf3a-0cfd90456613]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-58d51aca-8596-4d2c-bf3a-0cfd90456613.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-58d51aca-8596-4d2c-bf3a-0cfd90456613.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'loganalyticsdefaultresources'
      workspaceName: 'offboardingtestamirs'
      workspaceId: '09bede1a-81d2-4f6a-b2fa-c5274adcc234'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzurePPE'
      contentTypes: 'CustomDetection'
      branch: 'main'
      sourceControlId: '58d51aca-8596-4d2c-bf3a-0cfd90456613'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    # - name: Login to Azure (Attempt 1)
    #   continue-on-error: true
    #   id: login1
    #   uses: azure/login@v2
    #   with:
    #     client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_58d51aca85964d2cbf3a0cfd90456613 }}
    #     tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_58d51aca85964d2cbf3a0cfd90456613 }}
    #     subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_9e534e7c28f34767982408109fb42cb5 }}
    #     environment: 'AzurePPE'
    #     audience: api://AzureADTokenExchange
    #     enable-AzPSSession: true
    
    # - name: Wait 30 seconds if login attempt 1 failed
    #   if: ${{ steps.login1.outcome=='failure' }}
    #   run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Add-AzEnvironment `
          -Name AzurePPE `
          -ActiveDirectoryEndpoint https://login.windows-ppe.net `
          -ResourceManagerEndpoint https://management.azure.com/ `
          -ActiveDirectoryServiceEndpointResourceId https://management.core.windows.net `
          -GraphEndpoint https://graph.ppe.windows.net/ | out-null;
          $oidcTokenParams = @{
           Uri            = $env:ACTIONS_ID_TOKEN_REQUEST_URL
           Body           = @{
                 audience = 'api://AzureADTokenExchange'
           }
           Authentication = 'Bearer'
           Token          = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN | ConvertTo-SecureString -AsPlainText
          }
          $IdToken = (Invoke-RestMethod @oidcTokenParams).value
          Connect-AzAccount -ServicePrincipal -Tenant ${{ secrets.AZURE_SENTINEL_TENANTID_58d51aca85964d2cbf3a0cfd90456613 }} -Subscription ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_58d51aca85964d2cbf3a0cfd90456613 }} -ApplicationId ${{ secrets.AZURE_SENTINEL_CLIENTID_58d51aca85964d2cbf3a0cfd90456613 }} -Environment AzurePPE -FederatedToken $IdToken | out-null;
          $context = Get-AzContext
          Write-Host "Connected Subscription Id: $($context.Subscription.Id)"
          Write-Host "Connected Subscription Name: $($context.Subscription.Name)"

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Add-AzEnvironment `
          -Name AzurePPE `
          -ActiveDirectoryEndpoint https://login.windows-ppe.net `
          -ResourceManagerEndpoint https://management.azure.com/ `
          -ActiveDirectoryServiceEndpointResourceId https://management.core.windows.net `
          -GraphEndpoint https://graph.ppe.windows.net/ | out-null;
          $oidcTokenParams = @{
           Uri            = $env:ACTIONS_ID_TOKEN_REQUEST_URL
           Body           = @{
                 audience = 'api://AzureADTokenExchange'
           }
           Authentication = 'Bearer'
           Token          = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN | ConvertTo-SecureString -AsPlainText
          }
          $IdToken = (Invoke-RestMethod @oidcTokenParams).value
          Connect-AzAccount -ServicePrincipal -Tenant ${{ secrets.AZURE_SENTINEL_TENANTID_58d51aca85964d2cbf3a0cfd90456613 }} -Subscription ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_58d51aca85964d2cbf3a0cfd90456613 }} -ApplicationId ${{ secrets.AZURE_SENTINEL_CLIENTID_58d51aca85964d2cbf3a0cfd90456613 }} -Environment AzurePPE -FederatedToken $IdToken | out-null;

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-58d51aca-8596-4d2c-bf3a-0cfd90456613.ps1

